### ISSUE TITLE
No complaints

### ISSUE THREAD

**Issue by iiAlphaWolf01** [Splamy/TS3AudioBot#110]
So since everyone is crying and only seeing bad things I just want to point out to all of you who haven't thank splamy first before crying. I mean have you ever seen a music bot for TeamSpeak like this that's not lagging and online? Nah don't think so.

Thanks you splamy for making this, maybe take a break or chill those people will find out by them selves if they are worth it lol. Have a nice day idk why but I just wanted to thank you alot.

Wirklich, danke... 

_Sent from my Samsung SM-N910F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Splamy** [comment]
Haha, thank you for your uplifting compliments ^^ !
Just on a side note, you dont need to (and neither do I) see issues so negatively, they are what they are: bug reports, improvement request and often just questions. They are essential for a growing project.

**Comment by iiAlphaWolf01** [comment]
True but some people are just so stupid and ask because they think asking is the fastest way to set everything up. I mean just try you know what I mean

_Sent from my Samsung SM-N910F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JABirchall** [comment]
People learn in different ways. Some people need their hand held while some and tinker to solve a problem.

Issues shouldn't been seen in a negative sense. It infact helps splamy to know that people are using his project and reporting bugs they find for him to fix. And by the amount of returning people to issues, shows that its a project of much desire. A free, Open source, Headless music bot.

Its innovative!

**Comment by Synergyst** [comment]
I love the project myself!
I am glad it's open-sourced for others to help improve it in places it may be lacking or buggy.

I have no complaints with the project as the development is very active.
And since it is open-source other can freely contribute to the project that Splamy has worked very hard for. ^^

I've slightly modified the bot to utilize RTL-SDR(another open-source project) and allow the bot to stream live FM radio!
Now there are many other things you can do with the bot obviously, however that's just a simple example. 😃
