### ISSUE TITLE
System.ArgumentOutOfRangeException: 'Number was less than the array's lower bound in the first dimension. Parameter name: srcIndex'

### ISSUE THREAD

**Issue by JABirchall** [Splamy/TS3AudioBot#121]
in Ts3Crypt line 184.

680 bots were started, 200 connected before that error was thrown.

https://i.imgur.com/PHqfMtK.png

If le-wants my code to show the error le can.

**Comment by JABirchall** [comment]
when skipping that exception a second one gets thrown straight away.
`System.ArgumentOutOfRangeException: 'Buffer is not large enough for this object.
Parameter name: mappedValue'` gets triggered in RingQueue

**Comment by Splamy** [comment]
Sure thing, I think it would really help if I can try out the code

**Comment by Splamy** [comment]
Ok I was able to reproduce the first error, I will look into it

**Comment by JABirchall** [comment]
Ill send you my project via email after work, What is your email?

**Comment by Splamy** [comment]
Ok, already got two bugs fixed yesterday but unfortunately my internet blacked out for a day.
So I can now push two fixes, one for the (prbobably the 1/100) bug which is the first one with the index out of bounds source. This one occours with some identities.
The other one was an overly protective receive window. I changed the implementation to simply drop packets instead of throwing an exception. Also the receive window buffer grows dynamically and has a maximum of twice the size.
The problem generally is here the same that when connecting the client gets one huge packet which is split up over many fragmented packets, at about 600 packets there are more than 50 packets i have to wait for before i can decompress the content. I set it to 10, so theoretically now it should handle up to 1200 packets probably.

**Comment by JABirchall** [comment]
Did you get my email with the source to test with?

**Comment by Splamy** [comment]
yes i got it, but i havent looked at it yet.

**Comment by JABirchall** [comment]
Update: With my fixes, I had 300 bots on my server idle for 2 days using 80mb ram and basically 0 cpu.

**Comment by Splamy** [comment]
> With my fixes6

what fixes do you mean ?

Also some notes:
this line `identity = Ts3Crypt.LoadIdentity(identity.PrivateKeyString, identity.ValidKeyOffset);` is redundant, you already have the identity when calling GenerateNewIdentity

this line `tsClientList.Add(tsFullClient);` is never executed since the connect call with dispatcher ExtraDispatchThread does not return

**Comment by JABirchall** [comment]
>Also some notes:
>this line identity = Ts3Crypt.LoadIdentity(identity.PrivateKeyString, identity.ValidKeyOffset); is redundant, you already have the identity when calling GenerateNewIdentity

>this line tsClientList.Add(tsFullClient); is never executed since the connect call with dispatcher ExtraDispatchThread does not return

Yeah, I found that out later. It was in plans so each bot would know each other for other functionality

**Comment by Splamy** [comment]
I have pushed the current work branch to master which includes the new queue implemenetation. It should work with up to ~700 clients connecting. At some point more the bot will not accept any more packets which will lead to either diconnecting or dropping him.
This behavior is intended because a very big (or unlimited) receive buffer might open DoS possibilities by flooding the buffer.
If you have any further problems or questions feel free to ask.
