### ISSUE TITLE
Maybe found an error :o

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#123]
https://github.com/Splamy/TS3AudioBot/blob/dbrework/PluginTests/Program.cs#L127 isn't that supposed to be = true?

**Comment by Splamy** [comment]
Fore one that files are already gone on the dev/master branch and were merely for playing around.
On the other side this is correct. `result.Errors` contains the count to errors **and** warnings, because warnings dont affect the compile process i logical or this variable out `containsErrors |= !error.IsWarning;` as long as each entry is only a warning (`false | false | false | ... | true`) <- as you see it has to start with false until one error sets it to true
