### ISSUE TITLE
Multiple instances - Minor bug

### ISSUE THREAD

**Issue by Najsr** [Splamy/TS3AudioBot#207]
Hey there, I have 2 instances of Audio Bot running on my server. When I play a song on one, both bots (even tho only one is playing a song) get as their avatar thumbnail image from the song.

**Comment by Splamy** [comment]
Yes, there is nothing I can do right now since the avatar is set by identity in teamspeak, and since all clients from the same ts3instance have the same identity, there is no way to assign them different avatars.
This will not occour anymore when each bot has its own id.
So I will close this since I will be fixed implicitly some time in the future
