### ISSUE TITLE
Guide (noobs) :/

### ISSUE THREAD

**Issue by Askeshine** [Splamy/TS3AudioBot#216]
Hello, this project is great! I would love to know how to make it work in Linux, use the Windows version and it's great to read what is below but I honestly do not understand, I must compile it to use it? is not already compiled?

I only need the Youtube Search system, some Plugins and be able to limit it by groups that can use it ....

**Comment by TheAsuro** [comment]
You don't need to compile it yourself, the download link of the build is at the top of the readme :)
You'll still need the dependencies though (mono version >5, libopus-dev and ffmpeg). Then you can start it with `mono TS3AudioBot.exe`

**Comment by Bluscream** [comment]
I think about providing a shell script that downloads all the stuff if noone has done that so far

**Comment by ronindesign** [comment]
For those not familiar with `mono` it might be helpful to explain this a bit.

Currently, front page looks like only way to use Linux is to compile (since its listed under the _Compile_ section).
Maybe move around or add note for this, even if just to say something like: _Use mono to run exe directly on Linux_

Or maybe break it into two sections, leave the full steps for compiling on Linux, but then have extra sub-section that shows exactly what's needed only for running on linux.

I think part of the confusion is, when going to get nightly build, there is no mention of OS, architecture, etc.
It's just a zip with EXE, so seems like the wrong thing at first glance from linux perspective.

Just some feed back from my first impressions! Thanks for all the work on this!
