### ISSUE TITLE
Few enhacements

### ISSUE THREAD

**Issue by zmechu** [Splamy/TS3AudioBot#245]
Splamy - great job with TS3AudioBot!

My proposals (some has been mentioned here):
1) [important] **auto-start music while bot join server**. So, when I've define music stream (!play <stream>), I'd like to bot "remember" this stream after connect/reconnect and start play automatically.
2) [important] bot should **remember last volume level**
3) [important] bot should **apply volume level to all streams**. Now I have volume level 10, add stream to play - and it plays with volume 10. Using "!volume 5" change volume of stream. Nice! But adding new stream it starts with default volume 10. Not nice.
4) [quite important] ability **decode and to set bot description with current song name** (not only stream name)
5) [not important but nice] **web interface**

Thank you in advance :-)

**Comment by Splamy** [comment]
Good suggestions, most of them are already in planning and have a open issue already
1. #238
1. This is mostly by design. When you play a very quiet song and set the volume up, the next song will definitely blow up your ears.
You can set the volume permanently with `!settings AudioFramework::defaultVolume <volume>`. But I'm thinking about adding an option to preserve volume
1. same
1. #200
1. #22

**Comment by HellBz** [comment]
Status of 1. ?

**Comment by Splamy** [comment]
I'm currently at rewriting the config, after that I have planned stabilizing the ffmpeg interaction, but I can squeeze in this feature.
I've updated the roadmap to reflect my current plans https://github.com/Splamy/TS3AudioBot/projects/2

**Comment by Splamy** [comment]
2. Is now customizeable.
All other requests are tracked in the other previously tagged issues.
For specific problems/questions please continue in the corresponding issue.
