### ISSUE TITLE
Optimal Production Hoster Setup

### ISSUE THREAD

**Issue by bennetgallein** [Splamy/TS3AudioBot#293]
Hey Guys,
I currently have the Job to develop a Webinterface for a Teamspeak Hoster. They want to sell TS3AudioBot as Musicbots. Now the challenge is up to me to figure out how to have an optimal Server Setup to manage more than one Instance. I thought about using Docker to create Bots dynamically but the challenge is to connect the Bot to a provided IP.
Also I thought about using different configs with entered IP and different Ports for WebAPI and launching the Bot in a screen or so.

Let me know if someone has experience with this topic and what your approach would be!

**Comment by Christian1998** [comment]
📌Interested

**Comment by Splamy** [comment]
Since noone actively hosting the bot wants to give a statement. I'll just give my 2 cents on how I imagined it could work.
The bot already has multi instance integrated, but with some limitations:
- The history is shared across all instances (maybe I'll add query filter to it someday)
- The permissions are shared across instances (but will be configurable later with the `server` perm matcher)
- CommandGroup and ResourceFactoriy plugins are shared across all instances

As well as even though the TS3AB is pretty stable, if there are any core problems multiple instances would be affected by this. (For for example a restart.)

Single core management on the other hand should be rather straight forward.
You can declare with the `rights.toml` file a master api key which is managed by the backend.
The backend could call `!bot connect new <ip/domain/nicknam> (<password>)` to connect to a new server. When the connect was successful the template can be saved with `!bot save <name>` (or as api for example `/bot/use/<botid>/(/bot/save/<name>)` because `bot save` is a bot instance method).
To enable or disable autostart when the entire core starts you can add a global config entry in `[Bots]` for example with `!settings global set Bots.<name>.run true` (hmm, just tested, this does not work yet, I will add it soon. Right now you can only edit this entry if it already exists)

If you want more stability and customizability for each user you could also try the Multi core approch, aka one `TS3AudioBot.exe` process for each user.
You'd have to place the binary and all dependencies in a folder, lets say `./Core`, and each new user gets a folder with all the configs `./User1/ts3audiobot.toml,ts3audiobot.db,etc..`.
You can easily use one generated config file as template and just paste the relevant text or get a toml library read the template and let it write the with the modifications.

**Comment by bennetgallein** [comment]
Thanks for the answer first off.
I'm probably gonna take the first approach, because it's easier for me to just create new instances. 
The only problems are the shared history and the shared permissions, which, as you could image, won't work that well in a production hosting environment. 
I'm willing to implement that solution as a public project, so everyone who is in the need of something in that direction has at least a starting point. 
Sadly, I'm not a C# developer otherwise I'd love to support further Development. Let me know if there are any updates that belong to this topic!
