### ISSUE TITLE
How working new !settings?

### ISSUE THREAD

**Issue by Mareczin** [Splamy/TS3AudioBot#303]
Hey i have a little question. How after updates now working command !settings?
How i can for example set DefaultChannel for selected instance? 
!settings QueryConnection::DefaultChannel - not working :(

Regards ;)

**Comment by koznov** [comment]
For not duplicating i will reopen this issue, ok?
In latest stable version : 
Version: 0.8.1
Branch: master
CommitHash: cb1448a5c30edf4649f8f49fa4c0212096764515
there is no help commands for !settings 
And !settings is not working anymore : 
<02:55:23> "TS3 Support ": !settings AudioFramework::AudioMode=voice
<02:55:23> "MusicBot-123": Error: No config key matching the pattern found

**Comment by Splamy** [comment]
@koznov The master (0.8.1) you are running is still using the old settings system.
Replace the `=` with a ` `(space) to set a value.

This issue is referring to the new settings system. If you update and encounter the same problem look into #305.

**Comment by koznov** [comment]
@Splamy ok, thanks.
I'm trying to set default room for bot but still no success. In config there is this manual for:
```
# Default Channel when connectiong
# Use a channel path or '/<id>', examples: 'Home/Lobby', '/5', 'Home/Afk \/ Not Here'
```

and i'm trying to set it via message:
![image](https://user-images.githubusercontent.com/16073136/42917320-b8484042-8b11-11e8-95af-078be6761fcb.png)

```
<05:07:38> "TS3 Support": !settings QueryConnection:efaultChannel '/21516'
<05:07:38> "MusicBot-123": Error: Found more than one matching key: 
  QueryConnection:efaultChannel
  QueryConnection:efaultChannelPassword
```

**Comment by koznov** [comment]
And without quotes same situation (only /21516)

**Comment by Splamy** [comment]
1. `QueryConnection:efaultChannel` looks like a typo, it should be `QueryConnection:DefaultChannel`
2. Single quotes `'` do not work
3. Nonetheless there is a bug on the master branch, this is the only setting you can't set via command because of that :/

Either set it manually in the config for now, or get the latest develop branch build (careful the develop branch has the completely new settings system. Automatically upgrading the configs only works one way; backup files will be create though)
