### ISSUE TITLE
YouTube error.

### ISSUE THREAD

**Issue by dzinks2009** [Splamy/TS3AudioBot#402]
**Describe the bug**
https://www.youtube.com/watch?v=E1OjQ_3kh4A - When I try to play this song I get (youtube: youtube-dl failed to load the resource.)

**To Reproduce**
!play https://www.youtube.com/watch?v=E1OjQ_3kh4A

**Version**
Version: 0.9.0-alpha.78
Branch: develop
CommitHash: 63dc0ee2fcf3eb498a33d4c65db00a583c690ca8

**Platform**
Ubuntu 16.04

**Log**
```
018-10-14 22:38:41.6116|WARN|WebWrapper.ToLoggedError Web error: [403] Forbidden
2018-10-14 22:38:41.6126|DEBUG|YoutubeFactory.YoutubeDlWrapped Falling back to youtube-dl!
2018-10-14 22:38:43.3965|ERROR|YoutubeDlHelper.RunYoutubeDl youtube-dl failed to load the resource:
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
```

**Comment by Splamy** [comment]
Unfortunately I cannot reproduce this bug.
This problem seems to be youtube-dl related. Could you try updating youtube-dl? (Usually the youtube-dl from the ubuntu package manager ist very up to date; your best bet would be to just download the latest version from the website if you aren't already doing this)
if this `youtube-dl --no-warnings --get-title --get-url --format bestaudio/best --id -- E1OjQ_3kh4A` doesn't yield you any link, you could report this to the youtube-dl repo.
