### ISSUE TITLE
MusicBot 0.9.1 Keeps looing older songs.

### ISSUE THREAD

**Issue by iiAlphaWolf** [Splamy/TS3AudioBot#421]
Hello,

So i downloaded the newer version of the music bot because i had an old one. But the problem now is that whenever i play a song it working fine but when i do like 10 more !play it keeps repeating older songs i started with this command.

Example:
!play link1
!play link2

adter song link2, link1 goes on..

**Comment by Splamy** [comment]
Yes, I recently found this behaviour too, I hope that I can fix it the next few days.

**Comment by iiAlphaWolf** [comment]
Maybe "!repeat" or "!loop" problem not responding to prefix: "off"

**Comment by Splamy** [comment]
`!loop` does not exist anymore, see here for all bigger changes: https://github.com/Splamy/TS3AudioBot/wiki/Changelog
`!repeat` should work as intended.
There's something off with the internal indexing...

**Comment by P-Kito** [comment]
I KNEW IT...

I opened the issue here, but was unsure if its a problem on my side or your side 
https://github.com/Splamy/TS3AudioBot/issues/398

💃

**Comment by P-Kito** [comment]
https://github.com/Splamy/TS3AudioBot/commit/d45044984877fa07fa3675371349c52bda632560#diff-f426d5a76d897b0bf0aeaa338da6bcb5

Related to this?

**Comment by Splamy** [comment]
Probably, but I'm still trying to figure out what actually went wrong

**Comment by Splamy** [comment]
Waah, this bug is so random, I can't reproduce it. But that's ok, I've planned a .queue handling rework anyway since it's somethimes really bad right now.

(some naming hint: lists starting with a dot like `.name` are reserverd special lists)
Here is my current idea:
- `.queue` is not the global all-in-one list anymore
- instead, songs called with `!add` are pushed onto `.queue`
- `!play` will now simply stop the current song and play the requested song. The new song will not be insert into `.queue`anymore
- The last played songs are still retrievable with `!history last <count>`
- 'random' and 'loop' now only affect manually started playlists, again because there is no global list
- When a song ends, the next song from `.queue` will be poped and played.
- When the queue is empy playback stops.
- Adding a song to the queue when nothing is running, will immediately pop and play the song
- As a result `!previous` doesn't work anymore when playing in queue-mode, since eveything gets poped from the `.queue` when it's played

Considerations:
- `!stop` will clear the current `.queue`. It might be weird if someone starts a song and after a `!stop` and the queue suddenly continues.

**Comment by P-Kito** [comment]
So ".queue" = "!add" ?? x)

**Comment by Splamy** [comment]
To be fair the current `!add` aready works like a queue too. It's just that it might haver weird side effects

**Comment by iiAlphaWolf** [comment]
Can't wait to test it my music bots keep looping those stupid Christmas songs 😂😂

**Comment by Splamy** [comment]
I've recently pushed the queue rework to develop.
The `!info` command is new and shows a small summary of the playlist and queue.
`!song` has been revamped packing more information into one command.
