### ISSUE TITLE
what OnErrorEvent makes?

### ISSUE THREAD

**Issue by garko32** [Splamy/TS3AudioBot#429]
I am currently working with the TS3ClientTests file and wondering what OnErrorEvent outputs to me, it does not show that the client is flooding

**Comment by Splamy** [comment]
That's because the `OnErrorEvent` only gives you as the name says events. An error which you didn't cause or rather initiated.

The flooding error happens as the result of an action you send. Therefor the error will be returned to the action you called.

Simple example:
```csharp
using TS3Client;
using TS3Client.Full;
using TS3Client.Helper;
using System;

namespace Ts3ClientTests
{
	public static class FloodingTest
	{
		public static void Main(string[] args)
		{
			// Initialize client
			var client = new Ts3FullClient(EventDispatchType.AutoThreadPooled);
			var con = new ConnectionDataFull() { Address = "127.0.0.1", Username = "TestClient", Identity = Ts3Crypt.GenerateNewIdentity() };
			client.OnConnected += Client_OnConnected;
			client.Connect(con);
		}

		private static void Client_OnConnected(object sender, EventArgs e)
		{
			var client = (Ts3FullClient)sender;
			for (int i = 0; i < 100; i++)
			{
				var result = client.SendChannelMessage("Hi");
				if (!result.Ok)
				{
					Console.WriteLine(result.Error.ErrorFormat());
					Console.ReadKey();
				}
			}
		}
	}
}
```

This will print `client_is_flooding: the command failed to execute: client is flooding` to the console.
The error happens when you try to send the channel message, but that exact action fails. So you get an error return code for that call.

**Comment by garko32** [comment]
thanks i have another question how i can display the Md5 from uploadavatar in Console.WriteLine

**Comment by Splamy** [comment]
The UploadAvatar function does not provide those information.
However you can look up in the implementation how to do it manually:
https://github.com/Splamy/TS3AudioBot/blob/develop/TS3Client/Ts3BaseClient.cs#L263-L270

**Comment by garko32** [comment]
i dont know what its mean with stream image can you help me please

**Comment by garko32** [comment]
my last question is can i play music without libopus? thanxs

**Comment by Splamy** [comment]
No, libopus is the default audio encoding ts3 uses. You can alternatively implement speex or celt, but that would be some work.

**Comment by garko32** [comment]
okay thanx you!
