### ISSUE TITLE
Send bot audio to X servergroup.

### ISSUE THREAD

**Issue by dalexhd** [Splamy/TS3AudioBot#469]
I´m trying to send the bot audio, to X ts3 servergroup. Which exact command do i need to use for that?

**Comment by Bluscream** [comment]
<18:50:37> "Bluscream 🍭": !help whisper
<18:50:37> "[Pizza Boy ♥] Pizza Boy ♥": The command contains the following subfunctions: all, group, list, off, subscription

**Comment by dalexhd** [comment]
I know that, but doing "!xecute (!next) (!whisper group ServerGroup AllChannels 9)", doesn't work...

**Comment by Splamy** [comment]
The command works fine for me. You should check your whisper permissions on the server.

**Comment by dalexhd** [comment]
The bot should debug insufficient permissions?

**Comment by Splamy** [comment]
No, it can't. How should he know who he can whisper to, when you set a ts3group as the whisper target?
It's the same with a normal client. When you would whisper to a ts3group, the server would send to all clients in that server group, but filter those tagets which you can't whisper to, due to missing whisper power.
The server does not give you any response or warning. Only when the target set is empty.
