### ISSUE TITLE
Show list with name

### ISSUE THREAD

**Issue by djagiello** [Splamy/TS3AudioBot#473]
I'm not sure if it's a bug, or rather a suggestion.
1. I download a list from youtube
2. Change its name to "test"
3. ! List show "test" /! List show test does not work

Does the bot have multiple list management? Or can only operate on one list assigned to the user?

**Comment by Splamy** [comment]
When you load a playlist from whereever (youtube, local, etc) it will be loaded as a local worklist for you. This list cannot be accessed by anyone else.
`!list name <name>` only renames the the list for you in your workspace; the name is only used when you write `!list save`.
Basically `!list save <name>` is the same as `list name <name>` then `!list save`
Ergo, you can write `!list show` to show it if the list is in your workspace. Or write `!list save <name>` to save it on the disk, so that other can write `!list show <name>`
