### ISSUE TITLE
Loop function dont work

### ISSUE THREAD

**Issue by SylvanoP** [Splamy/TS3AudioBot#511]
Hello @Splamy!

I have a problem if i turn on the repeat function (/repeat/all) and then play a song (/play/{url} or /add/{url}) it stops after 1x playing.
How I can fix that?

Version: 0.9.1
Branch: master
CommitHash: ad86914f85f6a9dcea462d79e29f6da00eaecef7

**Comment by Splamy** [comment]
The list and queue mechanics have been reworked since many users were annoyed that songs randomly start/stop or loop.
To get looping behaviour, prepare an empty playlist (`!list clear`) add your songs (`!list add blub.mp3`) set the looping mode to either `!repeat one|all|off` (you can change that at any time) and start the playlist with `!list play`
Features like modifying the shared current playlist are still bit in progress
