### ISSUE TITLE
Delete the error message

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#522]
Where can I remove the error message completely?
![Unbenannt](https://user-images.githubusercontent.com/42515450/54774633-7b180100-4c0c-11e9-80b8-f2e8071c95f2.PNG)

**Comment by Flakebi** [comment]
The first thing you can always do (which I also do in projects I don’t know) is searching for strings in all files in the repository.
If you want to remove all error messages, you can try to search for `Error: `, including the space after the colon.
The GitHub search is not really suited for this as it ignores any symbols but Code Editors like VSCode are able to do this.

You will find 8 results, 2 of them in the localization file (which are probably the ones you search, because the error messages are shown to the user).

From there it requires only one more search to find the code where an error is written. I will leave this as an exercise to the reader :)
