### ISSUE TITLE
The TS3AB is not handling Web Requests anymore after some time

### ISSUE THREAD

**Issue by RageTimmy** [Splamy/TS3AudioBot#527]
**Describe the bug**
After some time the TS3AB does not handle Web Requests anymore, so it does not work anymore.

**Platform**
Debian 8
Mono JIT compiler version 5.18.0.268 

2 Hosts crashed last night, so I send both logs right now. 

First one: https://hastebin.com/eyegijoqej.coffeescript
Second: https://hastebin.com/icoyobejof.sql

And what does "Dropping not decryptable packet" mean? I hope that someone can fix this error because this bug is so annoying. It was not the first time, the last maybe 4 Days all Hosts worked operationally and then this happened again..

Thanks a lot!

**Comment by Splamy** [comment]
Which verison are you running `mono TS3AudioBot.exe -V`?

Apart form that, I can't see any crashes or problems in the log, except for some bots which don't have enough permissions to work

> "Dropping not decryptable packet"

happens when packets get send to a client which he can't read. This might have many reasons, often it's if a connection doesn't get closed correctly and the server sends packets to a port where a new bot runs.

**Comment by RageTimmy** [comment]
We are using Version 0.9.0. But why is the TS3AB crashing? How can I fix the missing Permissions?

**Comment by Splamy** [comment]
Resolved as per #532 too old version
