### ISSUE TITLE
catch audio in plugin

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#598]
How to catch the audio in a plugin before this audio is played in the bot, handle with them in realtime and play it?

**Comment by Splamy** [comment]
All pipes for audio processing are declared here:
https://github.com/Splamy/TS3AudioBot/blob/e024a1cc924fbcfd7eacca98aaa74d8d2afbaa0d/TS3AudioBot/Ts3Client.cs#L64-L70
and you can see how they are chained together here:
https://github.com/Splamy/TS3AudioBot/blob/e024a1cc924fbcfd7eacca98aaa74d8d2afbaa0d/TS3AudioBot/Ts3Client.cs#L104-L105

unfortunatle they are all private, since I haven't yet considered if and how those pipes should be public, which mean you would have to get them with reflection. For example
```csharp
// get the Ts3Client via injection:
Ts3Client ts3client { get; set; }

// ...

// (In your method:)
// Choose two pipes inbetween you want to insert your own pipe.
// Get the pipes with reflection:
var volumePipe = (VolumePipe)typeof(Ts3Client).GetField("volumePipe", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(ts3client);
var encoderPipe = (EncoderPipe)typeof(Ts3Client).GetField("encoderPipe", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(ts3client);

// Now you can insert your own pipe where you modify or read stuff here:
volumePipe.Chain(yourpipe).Chain(encoderPipe);
```

To learn how to write own pipes look into the Audio folder of the Ts3Client and read though the already available pipes. A very simple one for starters is the [CheckActivePipe](https://github.com/Splamy/TS3AudioBot/blob/e024a1cc924fbcfd7eacca98aaa74d8d2afbaa0d/TS3Client/Audio/CheckActivePipe.cs) which does nothing but check if the next pipe in the line is active and if not, returns. This effectively stops the propagiation of audio samples, to for example save outgoing bandwidth.

**Comment by marv-th** [comment]
Thanks for that. Do you know how to handle with the variable encoderPipe in naudio or cscore ?
I want to build an equalizer plugin where i can set the bass or treble (#546) 
Or do u allready know how to set bass, treble in ffmpeg.. i cant find anything in google

**Comment by Splamy** [comment]
I haven't worked with either audio library more in depth. But they both have a documentation and an examples project iirc

To your ffmpeg question, I found multiple results in less than a minute.
https://ffmpeg.org/ffmpeg-filters.html#anequalizer
https://superuser.com/questions/695843/how-to-use-equalizer-on-ffmpeg
https://lists.ffmpeg.org/pipermail/ffmpeg-user/2014-May/021329.html
(the second two probably need some more work as 'equalizer' was deprecated for 'anequalizer' and 'firequalizer')

**Comment by marv-th** [comment]
Thx ;) I will try this in the next time. Maybe i can post my working result for #546 if you want

**Comment by Splamy** [comment]
Sure

**Comment by marv-th** [comment]
I tried many things but nothing works. I dont understand and can't find, where the ffmpeg arguments in your codes where set. If i look in htop there i can see (when the bot is currently playing audio) the ffmpeg command.
Maybe u can help me again.

**Comment by Splamy** [comment]
Here are the constant parameter for normal / icy streams:
https://github.com/Splamy/TS3AudioBot/blob/cb97fd4f34cb975324e90cbc5d101e4a168a6852/TS3AudioBot/Audio/FfmpegProducer.cs#L31-L33

Here is where they are passed for normal streams:
https://github.com/Splamy/TS3AudioBot/blob/cb97fd4f34cb975324e90cbc5d101e4a168a6852/TS3AudioBot/Audio/FfmpegProducer.cs#L196
Here for icy streams:
https://github.com/Splamy/TS3AudioBot/blob/cb97fd4f34cb975324e90cbc5d101e4a168a6852/TS3AudioBot/Audio/FfmpegProducer.cs#L247

And this starts the ffmpeg process:
https://github.com/Splamy/TS3AudioBot/blob/cb97fd4f34cb975324e90cbc5d101e4a168a6852/TS3AudioBot/Audio/FfmpegProducer.cs#L261-L278
