### ISSUE TITLE
Bot won't play the song

### ISSUE THREAD

**Issue by heartles39** [Splamy/TS3AudioBot#600]
I need immediate help. I sing a song to the bot, but it won't pick up. Youtube-dl file updated But it's still the same

Bot detects command but does not play song Pls help me

**Comment by Flakebi** [comment]
@heartles39, you want that people here take some of their free time to answer your questions. We are making this project because we are having fun with programming. There is no company behind this which pays for writing code or giving support. This means the time we can spend on this project is rare and precious.

As someone who uses the bot and wants to contribute to this project, you have multiple options. You can insist on getting help because something does not work. And you can do this without providing any valuable information apart from 'does not work'. Inevitably, nobody can help you solving your issue because noone knows what is wrong. These issues worsen the mood of any involved developer, he wants to spend his rare time on important things and he wants to have fun, not getting blamed for writing his code for free.

Or you can spend more than the minimal amount of time yourself. Friendly describe your problem and add any information that might help us to understand what’s going on. This includes the version of the software you are using, an excerpt from the logfile and everything that helps a developer to reproduce the bug. If a bug can be reproduced, it will get fixed a lot easier and faster.

Please consider this when you open an issue on an open source project. The choice is yours.

**Comment by marv-th** [comment]
Is that problem on every song or even some songs? If you had this problem on only some youtube videos, than this is a current YouTube dl bug

**Comment by Bluscream** [comment]
just found this in the vvda2 channel lmao
