### ISSUE TITLE
Wie aktiviere ich den Webserver für die API?

### ISSUE THREAD

**Issue by NiclasPe** [Splamy/TS3AudioBot#608]
Heyy, erstmal geiler Bot mach weiter so.

Aber wie kann ich den Webserver für die API akvieren bzw. wo muss ich Apache hin leiten?
Denn mein First encoder Webinterface kann nicht auf die API zugreifen. 

Infos:
noch nix am Installieren Bot geändert. 

Finde den Webser und die Config nicht.

**Comment by Splamy** [comment]
The current develop branch has the webserver enabled by default on port `58913`. If it's not running there I assume you downloaded the current master or github release one.

Those are the two settings you have to set to true.
```toml
[web.api]
enabled = true

[web.interface]
enabled = true
```

On a side note, since *a lot* has changed comparing the current master to develop, especially with the webserver, my information might be outdated.
I'd suggest you to try out the latest develop build from our nighly server, or, as we are moving from mono to dotnet core as the primary runtime framework anyway, the latest develop_dotnet_core branch.
Both available here: https://splamy.de/Nightly#ts3ab
Instructions on how the set up everthing with dotnet core instead of mono is available in the develop readme: https://github.com/Splamy/TS3AudioBot/tree/develop#install

The develop verion might have a few braking changes compared to the current master, but final feature additions are currently made and everything will be merged back to master hopefully soon when I have time again to write more.

**Comment by NiclasPe** [comment]
ok, Thx
