### ISSUE TITLE
Bot Crashed

### ISSUE THREAD

**Issue by ReapCode** [Splamy/TS3AudioBot#641]
Mein Bot Probiert den Link abspielen aber er gibt nur Fehler aus! Irgendwelche Idee das zu Fixen??

10:31:30.9229| WARN|| Web error: [403] Forbidden
10:33:39.9487| INFO|1| Song queue ended: No next song could be played.
10:33:41.2715| WARN|| Web error: [403] Forbidden
10:35:49.9762| INFO|1| Song queue ended: No next song could be played.
10:35:51.2759| WARN|| Web error: [403] Forbidden
10:37:53.9640| INFO|1| Song queue ended: No next song could be played.
10:37:55.2868| WARN|| Web error: [403] Forbidden
10:40:04.7703| INFO|1| Song queue ended: No next song could be played.
10:40:06.0791| WARN|| Web error: [403] Forbidden
10:42:15.2568| INFO|1| Song queue ended: No next song could be played.
10:42:16.5162| WARN|| Web error: [403] Forbidden
10:44:25.4090| INFO|1| Song queue ended: No next song could be played.
10:44:26.6755| WARN|| Web error: [403] Forbidden

**Comment by Flakebi** [comment]
Hi, please try to keep issues in english, not everyone here understands german.
Also, please give us the requested information from the issue template. A lot of important information are missing, e.g. bot version, which link are you playing, etc.

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**To Reproduce**
Steps to reproduce the behavior (if possible)

**Version**
Which commit did you build or download? (mono TS3AudiBot.exe -V or !version in chat)

**Platform**
Which platform(-version) are you running on? (ubuntu 16.04, arch, windows,...)
Which runtime(-version) are you using? (mono: mono -V, dotnet: dotnet --info)

**Log**
```
Paste the important log parts from the ts3audiobot.log into this code block here.
Try not to paste too little.
At best from the first to last interaction from you which reproduces this problem.
```

**Comment by ReapCode** [comment]
And not everyone understands German !!
And please next time friendly thanks

**Comment by Flakebi** [comment]
@ReapCode I guess you meant to say not everyone understands english?
If you want help in german, there is a Gitter channel here: https://gitter.im/TS3AudioBot/Talk-GER
We try to keep the issues in english because often they are helpful for other people too, and we don’t want to limit that to german-speaking people.

Also, I didn’t want to be rude, the problem is that I cannot tell what went wrong just from the few log lines you supplied.
To answer the question from your first post, no, I have no idea how to fix that.
But I might get an idea if you tell me which link you want to play.
This is why I asked for more information.

**Comment by ReapCode** [comment]
Thank you for the information.
That should not be rude to me, I just wanted to share it
