### ISSUE TITLE
Question - advanced rights

### ISSUE THREAD

**Issue by zmechu** [Splamy/TS3AudioBot#647]
Hello!

I want to build quasi-advanced rights rules. Got sth like that:
```
# right definition
"+" = [ (many rights here) ] 

# Admin rule
[[rule]]
        groupid = [ (Admins group here) ]
        "+" = "*"
```
And I want to:
- **all users** should have "cmd.bot.connect.template" rights
- only **selected groups** should have "may rights" rights
- and **Administration groups should HAVEN'T** any rights, too :-)

```
[[rule]]
bot = [ "BotName" ]
        [[rule.rule]]
        "-" = "*"
        "+" = [ "cmd.bot.connect.template" ]

        [[rule.rule.rule]]
        groupid = [ (selected groups) ]
        "+" = [ (many rights here)   ]
```
It should do such:
- here we have BotName with rule: disallow anything anyone!
- but allow "cmd.bot.connect.template" anyone
- nest rule - additionally allow "selected groups" everything
... but why Admin groups still have permisions! What is wrong here?

Best regards!

**Comment by Bluscream** [comment]
Probiers mal auf deutsch, dein englisch kann ja kein mensch entziffern

**Comment by zmechu** [comment]
Von Google Translate:
Ich suche nach einer solchen Konfiguration

- Alle Benutzer sollten die Rechte "cmd.bot.connect.template" haben
- Nur ausgewählte Gruppen sollten "viele Rechte" haben
- und Admin-Gruppen sollten auch KEINE Rechte haben

Es ist für Event-Bot, wo zum Beispiel niemand (außer Event-Group!) Die Playlist sehen konnte. Aber jeder kann den ausgewählten Befehl trotzdem verwenden.

**Comment by Splamy** [comment]
Sorry about the late respone, I kind of forgot about this post.

> all users should have "cmd.bot.connect.template" rights

if you want to give a permission to all users put it in the root rule (the section before the first `[[rule]]`). So in your example:
```toml
"+" = [ (many rights here) ] # <- add it here
```

> only selected groups should have "may rights" rights

Create a new rule and add a matcher and the permissions you want to grant. For example
```toml
[[rule]]
    uid = [ "useruid1", "useruid2", ... ]
    "+" = [ ... ]
```
if you want those permission to be only on a specific bot, you can put it into a subrule which filters by bot:
```toml
[[rule]]
bor = "botname"
[[rule.rule]]
    uid = [ "useruid1", "useruid2", ... ]
    "+" = [ ... ]
```

> and Administration groups should HAVEN'T any rights, too :-)

```toml
        [[rule.rule]]
        "-" = "*"
```

i assume you are trying to remove the permissions of admins here again.
However this will not work as top level rules (all `[[rule]]` declarations) are always 'fully evaluated' and the permissions are added together.
See the example here in the wiki: https://github.com/Splamy/TS3AudioBot/wiki/Rights#merging-rules

You'll probably have to remove the admin rule and match admin permission differently.


On a side note:
Over the past time since the new permission system was released I observerd what was possible with the rigts system, what not and what people try to do with it.
I can see that it has quite some flaws and will try to fix all up in a bigger rework.
However I'll try to get it done in one swoop when I integrate the permission system to the api and the webinterface to minimize the span of breaking changes

**Comment by zmechu** [comment]
TX! :-)
