### ISSUE TITLE
Error bot

### ISSUE THREAD

**Issue by x-Scripts** [Splamy/TS3AudioBot#654]
Hello i'm problem a start bot

Unhandled Exception:
System.TypeLoadException: Could not load type 'TS3AudioBot.Helper.Environment.SystemData' from assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'.
  at TS3AudioBot.Core.Main (System.String[] args) [0x0000f] in <4538e9eac479412f9552eefaaeb01a98>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'TS3AudioBot.Helper.Environment.SystemData' from assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'.
  at TS3AudioBot.Core.Main (System.String[] args) [0x0000f] in <4538e9eac479412f9552eefaaeb01a98>:0

**Comment by Splamy** [comment]
Hey, please use our issue templates to provide us all information we need:

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**To Reproduce**
Steps to reproduce the behavior (if possible)

**Version**
Which commit did you build or download? (mono TS3AudiBot.exe -V or !version in chat)

**Platform**
Which platform(-version) are you running on? (ubuntu 16.04, arch, windows,...)
Which runtime(-version) are you using? (mono: mono -V, dotnet: dotnet --info)

**Log**
(already incuded)

**Comment by x-Scripts** [comment]
Hello, the problem has already been solved by reinstalling the mono library
