### ISSUE TITLE
dotnet 3.X

### ISSUE THREAD

**Issue by EBLONIX** [Splamy/TS3AudioBot#680]
Can you implement the latest version of DotNET? I would like to use Debian 10 and not 9 or Ubuntu. Also, the 2.2 is in maintenance.

**Comment by Splamy** [comment]
Definitely planned, however I wanted to round up 0.11.0 (which won't be a huge patch, just a some quality of life and maintanance changes) before switching to core 3.0.
If it was about me I'd areadly switched the day it was released, but there are a lot of users still depeding on older platforms.
Since we're already targeting 3.0 I can see if I can add a peliminary develop_3_0 branch into our build pipeline

**Comment by Splamy** [comment]
There's a `develop_dotnet_core_3_0_preview` branch now until we completely swap
