### ISSUE TITLE
Usage library YoutubeSearch

### ISSUE THREAD

**Issue by x-Scripts** [Splamy/TS3AudioBot#697]
Hello, I have a problem with plugins, what to do so that you can use the youtubesearch library?

**Comment by Splamy** [comment]
I don't understand your question. Also you should give more basic information like bot version, platform and what plugin exactly you are working with.

**Comment by infister** [comment]
He does not know how to search a song from youtube via command.
```
A: If you just want a !yt and !ytp/!yta command, simply add those two aliases:
!alias add yt "!search from youtube (!param 0)"
!alias add ytp "!x (!search from youtube (!param 0)) (!search play 0)"
!alias add yta "!x (!search from youtube (!param 0)) (!search add 0)"
```

**Comment by x-Scripts** [comment]
I wanted to use the YouTubeSearch.dll file in a bot plugin but when I use it immediately I get an error that I can't find this library

**Comment by Splamy** [comment]
You don't need any plugin for that. The bot already comes with this feature.
infister has copied a snippet from our wiki, see here for the full explanation https://github.com/Splamy/TS3AudioBot/wiki/FAQ#search-and-play-youtube-songs
You can use those aliases to create short helper snippets which makes the default commands easier to use.

**Comment by x-Scripts** [comment]
Ok, I will do that and the second thing is what you need to do to change the bot avatar if the music is not playing?

**Comment by Splamy** [comment]
I guess you mean `0.10.1-162`, since there is no 0.9.1with that revision tag.
In your version you can't change the sleep cover; however on the current develop you can create a folder called `avatars` and put image files starting with `sleep*`, so for eg `sleep1.png`, `sleepCat.png`. The bot will pick one randomly each time playback stops.

**Comment by x-Scripts** [comment]
In the sense I have this version 0.9.1-d72e8f73.1 + 162
I created the folder, uploaded the avatar and it did nothing

**Comment by Splamy** [comment]
As this issue is old and I want to close it, I want to point again to my previous comment:
Your version does not have this feature yet. Update to the current dev, then follow the comment.
(Also `0.9.1-d72e8f73.1+162` should be `0.10.0-alpha.162`; maybe you built it manually and the tag just got generated wrong, but in any case it does not have the new feature)
