### ISSUE TITLE
nginx - proxy pass

### ISSUE THREAD

**Issue by Ondra3211** [Splamy/TS3AudioBot#709]
**Describe the problem**
When I use proxy pass everyone can access the bot via webinterface without authentication

**System Information**
- **Platform**: Ubuntu 18.04 LTS
  
- **Mono version**: Mono JIT compiler version 6.6.0.161 (tarball Tue Dec 10 10:36:32 UTC 2019)

- **NGINX version**: nginx/1.17.5
  
- **Which commit did you download**:
Version: 0.11.0-alpha.39
Branch: develop
CommitHash: b34c7cd2ff5a46ac26981b98bd7b9393011749fc

In bot config:
```
hosts = ["127.0.0.1"]
```

In NGINX config:
```
    location / {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass         http://127.0.0.1:58913/;
    }
```

**Comment by Splamy** [comment]
Should be fairly simple:
Either configure nginx to forward the ip in the `X-Real-IP` header with
`proxy_set_header X-Real-IP $remote_addr;` instead of the `X-Forwarded-For`
Or remove the `ip` matcher from your rights.toml file ([looks like this](
https://github.com/Splamy/TS3AudioBot/blob/master/TS3AudioBot/Rights/DefaultRights.toml#L39))

I'll add a note in the wiki for that
