### ISSUE TITLE
add bot admin or something like that

### ISSUE THREAD

**Issue by 9ofe** [Splamy/TS3AudioBot#714]
way to give someone access to commands like !play !stop !pause
for a specific bot {not all the bots} 

and thanks <3

**Comment by Flakebi** [comment]
You can already do this in the `rights.toml` file with the bot matcher.
An example is here: https://github.com/Splamy/TS3AudioBot/wiki/Rights#example-1

**Comment by 9ofe** [comment]
my suggest is adding this to the interface website :)

**Comment by Flakebi** [comment]
Ah ok, at the moment it is not possible to add this easily because the permissions/rights are not accessible via the api (and the website is just a nice gui for the api).
But it is definitely planned to add this.

Configuring permissions on the website is already tracked in #651, so I’ll close this issue as a duplicate of the tracking issue.
