### ISSUE TITLE
Twitch does not play

### ISSUE THREAD

**Issue by ericmoros** [Splamy/TS3AudioBot#720]
**Describe the bug**
Twitch does not play

**To Reproduce**
!play https://www.twitch.tv/maddubztv

**Version**
0.10.0 alpha-snapshot

**Platform**
Windows 10

**Log**
```
22:06:43.1048| WARN|0| Web error: [410] Gone
```

You have to add oauth and remove the client-id header.
https://github.com/Franiac/TwitchLeecher/issues/403#issuecomment-552010508

**Comment by Splamy** [comment]
Thanks I'll look into it when i get to

**Comment by Splamy** [comment]
Kay, i fixed it the way i found here https://github.com/streamlink/streamlink/issues/2680
The issue is oauth won't work as there is no official api for geting the stream. This means twitch can break this at any time as they want, but there is no other option right now. We'll have to see what will happen. But for now it works again.
