### ISSUE TITLE
FATAL Critical program failure!

### ISSUE THREAD

**Issue by PyntoxHD** [Splamy/TS3AudioBot#728]
Hello I tried to install my TS3AudioBot the problem is that I get this error all the time : FATAL Critical program failure!
Can you help me please

**Comment by Flakebi** [comment]
Hi @PyntoxHD, there is a lot of information missing in your description.
Can you please fill out the issue template? We are unable to help you otherwise.

Here it is again for reference:

**Describe the bug**
A clear and concise description of what the bug is or what you expected to happen instead.

**To Reproduce**
Steps to reproduce the behavior (if possible)

**Version**
Which commit did you build or download? (mono TS3AudiBot.exe -V or !version in chat)

**Platform**
Which platform(-version) are you running on? (ubuntu 16.04, arch, windows,...)
Which runtime(-version) are you using? (mono: mono -V, dotnet: dotnet --info)

**Log**
```
Paste the important log parts from the ts3audiobot.log into this code block here.
Try not to paste too little.
At best from the first to last interaction from you which reproduces this problem.
```
