### ISSUE TITLE
Call script per websocket

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#769]
Hello. I want to call a php script that is filled on the server per webrequest. For example: if i call http://ip-adress:356/script.php?val1=abc call script -> /opt/bot/script_file.php
How can i do that. I think to do that with a plugin but how?
Thanks 😀

**Comment by Splamy** [comment]
Create a basic [plugin](https://github.com/Splamy/TS3AudioBot/wiki/Plugins) (since it's probably for global scope use `ICorePlugin`) or add a new command directly to the `MainCommands.cs` if you want to compile the bot maually.

In the command use something like [Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.8#System_Diagnostics_Process_Start_System_String_System_String_)
to run php. E.g. `Process.Start("php", "/opt/bot/script_file.php")` or similar.

**Comment by marv-th** [comment]
Yes that i know and already used. But i want to build an Upload interface
(de=Schnittstelle) and mean something different.
But i found a "better" solution to build this for our system.  Thank you 🙂

Splamy <notifications@github.com> schrieb am Fr., 17. Apr. 2020, 01:44:

**Comment by marv-th** [comment]
Yes that i know and already used. But i want to build an Upload interface
(de=Schnittstelle) and mean something different.
But i found a "better" solution to build this for our system.  Thank you 🙂
