### ISSUE TITLE
Datatype Problems

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#770]
We are currently rewriting our plugins for the new master version. Unfortunately we have to change all data types. On the one hand I noticed that the datatype was not changed in the ``TsFullClient.PokeClient`` function. I don't know if this is wanted or just forgotten.

My real problem is that I do not know how to work with these new datatypes. With standard datatypes of C# you can parse from a string into an ulong or similar, but how can I do that with the new datatypes? We would need that really urgently, otherwise we would have to rewrite everything completely

**Comment by Splamy** [comment]
Yeah, I oversaw the poke parameter, should be `ClientId`.
The idea behind these datatypes is, that they are more strongly typed than regular number types. For example you could accidentally pass a clientdbid to a function which wants a servergoupid, just because both types are a ulong. With these wrapped types this can't happen and the compiler will give you an error.
I've added the basic operator overloads wich make sense like equality checking. Since unlike numbers which you can compare with `<` or `>` doing this on those id types pretty much never makes sense.
To create one you only need a variable from the underlying datatype and wrap them with th constructor. For eg:
```cs
ushort myClientId = 4;
ClientId myClientIdTyped = new ClientId(myClientId);
// or uids:
var uidStr = "Splamy36QrG5AkF4uoS/h0fpHr0=";
var uidTyped = new Uid(uidStr);
```

**Comment by MoroseCorpse** [comment]
Okay, thanks, that helped a lot. But I just updated another issue of mine that was already closed:

https://github.com/Splamy/TS3AudioBot/issues/739#issuecomment-615269794
