### ISSUE TITLE
reduce the list in searching for Youtube song 

### ISSUE THREAD

**Issue by oscsystemx** [Splamy/TS3AudioBot#774]
**Describe the problem**
There is anyway to change the minimum list for searching? . At this time, there are 10 but i want to change it search only 1-3 i think it will save performace.
**To Reproduce**
-**-**

**System Information**
- **Platform**: (Ubuntu 18.04)  
  
- **Mono version**: (`6.8.0.105`)  
  
- **Which commit did you download**: (or on prebuilt: `0.12.0-alpha.19 - 14DA67FC`)  
 

![image](https://user-images.githubusercontent.com/48587121/79677645-d9ebe780-821d-11ea-9504-b02b020f0c87.png)

**Comment by Splamy** [comment]
Youtube-dl searches by downloading the search page in a specia json format. This results contains ~12 normal results + ~6 related results (which once returned by ytdl you don't know anymore which are what since ytdl just concats all together into one result list)
And since 10 is below that, it should never make more than one webrequest to youtube.
So unless you want to save a few cycles of parsing and formatting there's not much to save here.
