### ISSUE TITLE
Plugins dont work  

### ISSUE THREAD

**Issue by Silencesteal** [Splamy/TS3AudioBot#775]
What i do wrong?
I have the Plugin Folder, add the path in the config and
load with !Plugin load :(

![plugin](https://user-images.githubusercontent.com/63858091/79692900-0c223700-8268-11ea-9ac4-d67f971c339a.png)

**Comment by Splamy** [comment]
Since you have not said where you got your plugin from, may I guess that you got one of [BluScreams](https://github.com/Bluscream/TS3AudioBotPlugins) outdated ones, and as i take from the screenshot you also added a few random cs source files from the repo.
All the cs files which are not meant to be a plugin will not work and are not needed there either.
For the actual plugin (I guess the AntiAfK.cs) you will need to update it to work with your current version or find someone to update it for you.
If you want to get into plugin development, we have a wiki page here for that: https://github.com/Splamy/TS3AudioBot/wiki/Plugins

**Comment by Silencesteal** [comment]
Yes i have the Plugin form BluSreams xd 
hmm okey thanks for the help.
Do you have a PluginDownload site maybe? :)

**Comment by Splamy** [comment]
Someone already requested something like that: #756 but it's a lot of work to create so it's in the backlog for now
