### ISSUE TITLE
Bot is Lagging

### ISSUE THREAD

**Issue by Silencesteal** [Splamy/TS3AudioBot#789]
Hei Community :))

why is the bot lagging occasionally?
for example when i open the web browser or programs he is lagging a bit?

**Comment by Flakebi** [comment]
That’s because your internet is blocked for a short time and TeamSpeak audio packets get through later than expected.
In that time, TeamSpeak needs to send audio to your speakers but it did not receive it yet. A few milliseconds later (in the scale of 20–200ms), it receives these packets and plays them. The gap in between where only silence is played is what you can hear as crackling audio.

There is not really much that can be done about that, you can only trade latency for more robust audio.
If you would buffer audio for 1 second before playing, you would not have the crackling. Instead the talking experience would be a lot worse, people start talking at the same time because they don’t hear each other early enough (this is the experience you get with Skype and others).

Fun fact: The TeamSpeak client never decreases its buffer, so if you have a high enough latency at one point, the delay will stay until the audio stream is interrupted, i.e. the person stops talking and starts again. I observed a 6 seconds latency at one point.

**Comment by shoot991** [comment]
Would this be better with a loopback interface for the packet latency? The same server as teamspeak runs the bot.
