### ISSUE TITLE
Traffic savings

### ISSUE THREAD

**Issue by adrijanb** [Splamy/TS3AudioBot#835]
Unfortunately the TS3AudioBot is very traffic-intensive. The problem here is that if customers installs it on your server, the hosting company (if traffic is generated and calculated) will have to pay enormous costs.

Perhaps one could initiate traffic-saving measures here.

A suggestion from me would be, for example, sharing the same streams. We assume that there are 2 bots. One of these is currently playing the stream "stream.example.com". The 2 bot is created and tries to play the exact same stream, but before the 2nd bot downloads the entire stream again, it tries to access bot 1's stream download.

This could save a few GB of traffic :)

Furthermore, you may be able to put traffic-saving settings into operation in the TS3 client, so that there is a limitation on the part of the server or the client.

**Comment by Splamy** [comment]
This has already be requested a while ago here: #153 which since then went on the backlock because of not much attention.

> Furthermore, you may be able to put traffic-saving settings into operation in the TS3 client, so that there is a limitation on the part of the server or the client.

could you elaborate on that more?

The bot already tries to save as much as possible. When the channel is empty no voice is sent in normal mode. And in whisper mode when no targets are available the bot starts to sample poll for clients which is ~1/20th the bandwith usage.
You can also use the `onparty`/`onalone` events to start/stop the playback. This isn't done automatically since it could have side effects.

**Comment by zumoshi** [comment]
If I understand correctly, you want streams (e.g. an online radio) played by multiple bots simultaneously to be downloaded only once.
That can be achieved with [Icecast](https://icecast.org/). By disallowing users from linking to any outside stream directly. instead registering those links in Icecast and using the relayed link.
If you want it to be automated, a plugin could be made to preprocess the link, and if it was not a local (Icecast or self-hosted file) first connect to Icecast API to add it and replace the link with a relayed one.

**Comment by Flakebi** [comment]
I think all questions have been answered. I’ll close this in favor of #153.
