### ISSUE TITLE
Cant setup the master build

### ISSUE THREAD

**Issue by robotrono** [Splamy/TS3AudioBot#846]
Centos 7 x64:

Dotnet version is:

```
[teamspeak@servidor TS3AudioBot]$ dotnet --version
2.2.402

```

```
[teamspeak@servidor TS3AudioBot]$ dotnet build --framework netcoreapp2.2 --configuration Release TS3AudioBot
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/home/teamspeak/TS3AudioBot/TSLib/TSLib.csproj]
/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/home/teamspeak/TS3AudioBot/TS3AudioBot/TS3AudioBot.csproj]

```

**Comment by Splamy** [comment]
Well this is partially my past mistake since I choose to set the target for the project to dotnetcore2.2, but dotnetcore2.1 was the LTS version and the 2.2 version is now out of support and apparently the tooling broke.
The easiest fix is to change this
https://github.com/Splamy/TS3AudioBot/blob/4f17b2971e03bee94d1e630a2b5ce37d8a15e5ca/TS3AudioBot/TS3AudioBot.csproj#L5
and
https://github.com/Splamy/TS3AudioBot/blob/4f17b2971e03bee94d1e630a2b5ce37d8a15e5ca/TSLib/TSLib.csproj#L4
to
`<TargetFrameworks>netcoreapp2.2</TargetFrameworks>`
and build again.

I hope that I can get the develop back into the main branch dropping all old frameworks and only target dotnetcore3.1 which should make everything more straigtforward

**Comment by robotrono** [comment]
Thanks so much, works fine now! 

Command !playlist add was removed? @Splamy

**Comment by Splamy** [comment]
There newver was a `!playlist` command, you either had an alias or mean `!list add <name> <url>`. All list commands were changed at some point and now take the list name to modify as the first parameter
