### ISSUE TITLE
Unattended API token generation.

### ISSUE THREAD

**Issue by zumoshi** [Splamy/TS3AudioBot#861]
**Is your feature request related to a problem? Please describe.**
While the API is perfectly capable of creating new bots, currently the first bot has to be created manually (either through commands from stdin or modifying config files followed by restarting the server). And the API key can only be created by manually joining the TS server and sending a pm.

**Describe the solution you'd like**
The ability for an initial API token to be set before creating the first bot. This could either be from an environment variable (for a superuser) or a config file entry (ability to set permissions similar to the IP filter, but with a token followed by permissions it should have).

**Describe alternatives you've considered**
As stated in #818, If the admin connections were coming from a single IP, one could ignore the token altogether. but that is not always the case. (or in case of shared hosting, the admin may not be the only person able to use that IP)
Another alternative is to create an API token manually once with a dummy identity, then copy the database from that instance to any new instances created so they would come with a token. But this approach prevents the generation of a new random token for each instance reducing security.

---

The main use case is automated creation of new instances using an API, which would use the webapi to create new bots as soon as the instance is up. For example from a whmcs provisioning module.

**Comment by zumoshi** [comment]
A followup of this issue (feel free to ask me to create a separate issue for it if you want), is modifying rights through the API.
Assuming the server was created in unattended mode, There would be no UID in the roles file for the admin.

Ideally we wouldn't need to have a second web agent in the same server providing an API just for the purpose of modifying TS3AudioBot's config files from the provisioning module which may be on shared hosting and not have direct access to the files.

How to implement this is up to you, but these are some ideas:
- A method to read the `rights.toml` file. And a method to upload it, which would check the syntax, and if no errors replace the file and run `!rights reload`
- Specific methods to set each value, similar to the `settings` api. Something like:
    - `/rights/list` (list of rules)
    - `/rights/add` (creates new empty rule)
    - `/rights/del/{rule}` (deletes rule by id)
    - `/rights/get/{rule}/{path}` (e.g. `/rights/get/0/groupid` -> `[2]`)
    - `/rights/set/{rule}/{path}/{value}` (e.g. `/rights/set/0/useuid/%5B%22M8QUkY1Fx43ItB66HFFr0CimBDo%3D%22%5D`)
- Alternatively if you have more time the api can be more sophisticated, with methods to list all available permissions, or specific methods for adding a userid or group to a rule. rather than just replacing a json value in the toml file.

**Comment by Splamy** [comment]
I think all those changes here tie into the planned great rework of the permission system: #651 
Truth to be told, it's a feature already pretty long on the todo, but I want all currently open changes to be finished before I start something bigger again. And somehow my time planning is pretty bad so it keeps getting delayed.
But I hope to finish up on the last audio reworks soon, and with the upcomming release of .NET 5 I hope to get a new release before that, so I can switch the dev branch to .NET 5.

Could you transfer your two comments to the issue metioned at the top.
I don't know yet how much will change with the rework, but all feedback is appreciated and we will try to take it into account.

**Comment by zumoshi** [comment]
> transfer your two comments

As in just copy them and write duplicate comments in #651? Or did I miss something?

> I want all currently open changes to be finished before I start something bigger again

Can I help with your current open changes? From skimming develop branch's commits it seems the biggest changes were async and Icy streams. I don't have a lot of experience with low-level networking or ts3's protocols, but I can code some c#.
Feel free to tell me what to do and I'll clone the dev branch to see if I can or give me your ts info and a time if you think it's easier to explain it there than writing it.

**Comment by Splamy** [comment]
> As in just copy them and write duplicate comments in #651? Or did I miss something?

yes, exactly. Then I can close this issue, and still see that the two comments where from you in the other issue.

> Can I help with your current open changes? From skimming develop branch's commits it seems the biggest changes were async and Icy streams.

Hmm difficult, usually I'd say there's lots to help (see the huge issue backlog :P) but currently I'm working on the [buffer](https://github.com/Splamy/TS3AudioBot/commits/buffer) branch, since the develop branch should be kinda-semi-stable :P or at least I try to not break it on purpose when I can, and the audio pipleline improvements on the buffer branch currently break everthing.
And I too am struggling with the topic, since I try to build a modular, single threaded, high performance audio pipeline. Mostly just so I can easily add buffers into it as well as switch single pipe elements on the fly (for example a icy loader to youtube loader, or features like #153 where multiple pipes share the same source). The changes are also a result of the async rework before, trying to reduce thread usage overall, and make async behaviour more consistent.

In general if you see a nice issue you think you can implement or fix feel free to request to implement it with a comment, or make a empty pull request to the dev branch, and we can discuss what needs to be done for that issue and reserve it for you.
