### ISSUE TITLE
Convert incoming audio to a stream

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#866]
I would like to know if it is possible to get the incoming audio and convert it into a stream that can be used as a webstream for example.

The goal is to get the audio that the bot itself listens to and to pass it to a Discord Bot, which in turn plays it back and also intercepts the audio and passes it to the TS3Audiobot. So you could talk between Discord and TeamSpeak

**Comment by Splamy** [comment]
Yes you could do that, however you will need to implement some additional pipes for your case.
The basic overview would be
```csharp
// For receiving from TS and sending to a httpendpoint
client
	// This reads the packet meta data, checks for packet order
	// and manages packet merging.
	.Chain<AudioPacketReader>()
	// Teamspeak sends audio encoded. This pipe will decode it to
	// simple PCM.
	.Chain<DecoderPipe>()
	// This will merge multiple clients talking into one audio stream
	.Chain<ClientMixdown>()
	// Reads from the ClientMixdown buffer with a fixed timing
	.Into(new PreciseTimedPipe(SampleInfo.OpusMusic, Id.Null))
	// Reencode to the codec of our choice
	.Chain(new EncoderPipe(Codec.OpusMusic))

	// Sends the music to a http endpoint
	.Chain(new HttpTarget("https://discordbot.com/1"));
		// OR
	// Communicate via a tcp stream
	.Chain(tcpPipe);

// For receiving from a source and sending to ts
	// Read from httpserver
	new HttpSource("https://discordbot.com/1")
		// OR
	// Communicate via a tcp stream
	tcpPipe

	// Reads from the source with a fixed timing
	.Into(new PreciseTimedPipe(SampleInfo.OpusMusic, Id.Null))
	// Reencode to the codec of our choice
	.Chain(new EncoderPipe(Codec.OpusMusic))
	// Define where to send to.
	.Chain<StaticMetaPipe>(x => x.SetVoice())
	// Send it with our client.
	.Chain(client);
```

I think the communication via a tcp would be easier, otherwise you would need to set up a webserver on the discord bot side handling the in/outgoing streams.
You can also consider to use udp instead of tcp for the whole pipe, since working with audio data is usually more focused on latency instead of reliability, so dropping a audiopacket every once in a while is not a problem.

Note that the TSLib has no `HttpTarget`, `HttpSource` or `TcpPipe` classes. You would need to implement them to your needs.
Your tcp Pipe will need to implement `IAudioPassiveConsumer` for accepting audio data and sending it via tcp stream.
As well as `IAudioPassiveProducer` which provides the audio data comming from the tcp stream.
