### ISSUE TITLE
Assign more power to audiobot.

### ISSUE THREAD

**Issue by rentexgfx** [Splamy/TS3AudioBot#936]
**Describe the problem**
Bot lagging.

**To Reproduce**
1 | Run a bot.
2 | Run a game or web browser or something mid weight

**System Information**
- **Platform**: Windows 10 Pro
  
- **Mono version**: //
  
- **Which commit did you download**: //
  
I have a decent gaming PC and when I'm running bot at same time and opening Chrome or game, It starts lagging, just at startup of browser/game. Can I force bot use more CPU or something to avoid that lag? I have space on CPU and my CPU is not at 100% when I'm opening chrome or game.

I Tried to set Priority: to "High" or "Realtime" but no affect or deffect. And tried to set Affinity, but all my threads are checked.

**Additional Logs, Exceptions, etc**
//

```
Put logs or code in triple backticks like here to properly format it.
```

**Comment by Flakebi** [comment]
This can also be a problem of the internet connection/teamspeak. I can hear slight stutters when browsing imgur or opening websites, because the voice packets get slightly delayed (it also stutters for other talking people, not only for the audiobot). There’s nothing teamspeak can do, except increasing the buffer size, which also means increasing latency. Personally, I think keeping a low latency is more important (ms teams and others have a higher latency and it feels so much more clunky).
That is, unless your bot and your server are both running on your local pc?
